package Exception;

abstract class Game
{
	abstract void  play();
	
}
class Football extends Game
{
	public void play()
	{
		System.out.println("Play Football");
	}
}
class Cricket extends Game
{
	public void play()
	{
		System.out.println("Play Cricket");
	}
}
class Tennis extends Game
{
	public void play()
	{
		System.out.println("Play Tennis");
	}
	
}
public class GamesDemo 
{
	
	public static void main(String[] args) 
	{
		Game arr[]=new Game[3];
			arr[0]=new Football();
			arr[1]=new Cricket();
			arr[2]=new Tennis();
			//for(int i=0;i<arr.length;i++)
			//{
				arr[1].play();
			//}
			
		

	}

}
package Exception;

import java.util.Scanner;
class Myarithexception
{
	public void fun(int num)
	{
	   if(num==0)
	{
		   
		throw new ArithmeticException("Zero not allowed");
	}
	   else if(num<0)
	   {
		   throw new ArithmeticException("Negative not allowed");
	   }
	else
	{
		System.out.println("Number is valid");
	}
}
		
}

class Calculator
{
	public void caldouble(int a)
	{
		double b=(int)a;
		System.out.println("number is double"+b);
	}
}
public class MyCalcApp 
{

	public static void main(String[] args) 
	{
		System.out.println("Enter a number");
		Scanner sc=new Scanner(System.in);
		int num=sc.nextInt();
		Myarithexception m=new Myarithexception();
		m.fun(num);
		System.out.println("Number is"+num);
		Calculator c=new Calculator();
		c.caldouble(num);
	}

}
